all:
  children:
    backend:
      hosts:
        backend:
          ansible_host: 10.0.1.10
    edge:
      hosts:
        edge:
          ansible_host: 10.0.1.11
    db:
      hosts:
        db:
          ansible_host: 10.0.1.12
    redis:
      hosts:
        redis:
          ansible_host: 10.0.1.13
    search:
      hosts:
        search:
          ansible_host: 10.0.1.14
    workers:
      hosts:
        workers:
          ansible_host: 10.0.1.15
    monitoring:
      hosts:
        monitoring:
          ansible_host: 10.0.1.16
