stages:
  - tests

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  auto_cancel:
    on_new_commit: interruptible

tests:
  stage: tests
  image: python:3.11-alpine
  interruptible: true
  coverage: '/^TOTAL.+?(\d+\%)$/'
  before_script:
    - apk add --no-cache uv
    - uv cache dir
  script:
    - cd backend
    - make test-coverage
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ~/.cache/uv/
