all:
  children:
    backends:
      hosts:
        backend_dev:
          ansible_connection: local
    edges:
      hosts:
        edge_dev:
          ansible_connection: local
    dbs:
      hosts:
        db_dev:
          ansible_connection: local
    redises:
      hosts:
        redis_dev:
          ansible_connection: local
    searches:
      hosts:
        search_dev:
          ansible_connection: local
    workers:
      hosts:
        worker_dev:
          ansible_connection: local
    monitoring_nodes:
      hosts:
        monitoring_dev:
          ansible_connection: local