"""add column description in UserGroup

Revision ID: 0a000f0839e3
Revises: ed2b72d685b4
Create Date: 2026-03-26 17:54:14.486855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a000f0839e3'
down_revision: Union[str, Sequence[str], None] = 'ed2b72d685b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_groups', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_groups', 'description')
    # ### end Alembic commands ###
