"""Add table groups

Revision ID: 41b285d49669
Revises: 330ab5e92ef1
Create Date: 2026-03-02 20:18:44.593699

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41b285d49669"
down_revision: str | Sequence[str] | None = "330ab5e92ef1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_groups",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_groups_is_active"), "user_groups", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_user_groups_name"), "user_groups", ["name"], unique=True)
    op.create_table(
        "user_group_memberships",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["user_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("tasks", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.add_column("tasks", sa.Column("group_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_tasks_group_id"), "tasks", ["group_id"], unique=False)
    op.create_index(op.f("ix_tasks_owner_id"), "tasks", ["owner_id"], unique=False)
    op.drop_constraint(op.f("tasks_user_id_fkey"), "tasks", type_="foreignkey")
    op.create_foreign_key(None, "tasks", "user_groups", ["group_id"], ["id"])
    op.create_foreign_key(None, "tasks", "users", ["owner_id"], ["id"])
    op.drop_column("tasks", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("tasks_user_id_fkey"), "tasks", "users", ["user_id"], ["id"]
    )
    op.drop_index(op.f("ix_tasks_owner_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_group_id"), table_name="tasks")
    op.drop_column("tasks", "group_id")
    op.drop_column("tasks", "owner_id")
    op.drop_table("user_group_memberships")
    op.drop_index(op.f("ix_user_groups_name"), table_name="user_groups")
    op.drop_index(op.f("ix_user_groups_is_active"), table_name="user_groups")
    op.drop_table("user_groups")
    # ### end Alembic commands ###
