"""add notifications table and user groups invite policy

Revision ID: 4421e5aac69d
Revises: f1ed549f1e64
Create Date: 2026-04-02 01:41:53.398155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4421e5aac69d"
down_revision: Union[str, Sequence[str], None] = "f1ed549f1e64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create invite policy enum
    op.execute("CREATE TYPE invitepolicy AS ENUM ('ADMIN_ONLY', 'ALL_MEMBERS')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "GROUP_INVITE",
                "GROUP_JOIN",
                "TASK_INVITE",
                "COMMENT",
                "RATING",
                "FOLLOW",
                "MENTION",
                name="notificationtype",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("message", sa.String(length=255), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum("GROUP", "USER", "TASK", "COMMENT", name="notificationtargettype"),
            nullable=False,
        ),
        sa.Column(
            "response",
            sa.Enum("ACCEPT", "REFUSAL", "WAITING", name="notificationresponse"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("READ", "UNREAD", "FAILED", name="notificationstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_response"), "notifications", ["response"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_status"), "notifications", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_target_type"),
        "notifications",
        ["target_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_title"), "notifications", ["title"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_type"), "notifications", ["type"], unique=False
    )
    op.add_column(
        "user_groups",
        sa.Column(
            "invite_policy",
            sa.Enum("ADMIN_ONLY", "ALL_MEMBERS", name="invitepolicy"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_user_groups_invite_policy"),
        "user_groups",
        ["invite_policy"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop invite policy enum
    op.execute("DROP TYPE invitepolicy")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_groups_invite_policy"), table_name="user_groups")
    op.drop_column("user_groups", "invite_policy")
    op.drop_index(op.f("ix_notifications_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_title"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_target_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_status"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_response"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
