"""add deadline to tasks

Revision ID: 589fa531e9b8
Revises: ae6938fea45d
Create Date: 2026-04-05 21:06:10.222271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "589fa531e9b8"
down_revision: Union[str, Sequence[str], None] = "ae6938fea45d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("deadline", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "deadline")
    # ### end Alembic commands ###
