"""cleanup_membership_and_roles

Revision ID: 71a7c62aea57
Revises: eca64f6fa2dd
Create Date: 2026-03-29 04:42:19.457634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71a7c62aea57"
down_revision: Union[str, Sequence[str], None] = "eca64f6fa2dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_task_assignee", "task_assignees", ["user_id", "task_id"]
    )
    op.drop_index(
        op.f("ix_user_group_memberships_is_active"), table_name="user_group_memberships"
    )
    op.drop_column("user_group_memberships", "is_active")
    op.add_column(
        "user_roles", sa.Column("id", sa.Integer(), autoincrement=True, nullable=False)
    )
    op.drop_index(op.f("ix_user_roles_group_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_task_id"), table_name="user_roles")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_user_roles_task_id"), "user_roles", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_roles_group_id"), "user_roles", ["group_id"], unique=False
    )
    op.drop_column("user_roles", "id")
    op.add_column(
        "user_group_memberships",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.create_index(
        op.f("ix_user_group_memberships_is_active"),
        "user_group_memberships",
        ["is_active"],
        unique=False,
    )
    op.drop_constraint("uq_user_task_assignee", "task_assignees", type_="unique")
    # ### end Alembic commands ###
