"""add user skills table and task_spheres

Revision ID: ae6938fea45d
Revises: ed1cc5c53f35
Create Date: 2026-04-04 20:05:15.255945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae6938fea45d"
down_revision: Union[str, Sequence[str], None] = "ed1cc5c53f35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_skills",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "sphere",
            sa.Enum(
                "BACKEND", "FRONTEND", "DEVOPS", "QA", "PRODUCT", name="tasksphere"
            ),
            nullable=False,
        ),
        sa.Column("xp_total", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("streak", sa.Integer(), nullable=False),
        sa.Column("last_xp_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_frozen", sa.Boolean(), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "sphere", name="uq_user_sphere"),
    )
    op.create_index(
        op.f("ix_user_skills_sphere"), "user_skills", ["sphere"], unique=False
    )
    op.create_index(
        op.f("ix_user_skills_user_id"), "user_skills", ["user_id"], unique=False
    )
    op.add_column("tasks", sa.Column("spheres", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "spheres")
    op.drop_index(op.f("ix_user_skills_user_id"), table_name="user_skills")
    op.drop_index(op.f("ix_user_skills_sphere"), table_name="user_skills")
    op.drop_table("user_skills")
    # ### end Alembic commands ###
