"""fix user_roles id sequence

Revision ID: bfe899dccc6e
Revises: 4421e5aac69d
Create Date: 2026-04-02 19:03:26.858223

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bfe899dccc6e"
down_revision: Union[str, Sequence[str], None] = "4421e5aac69d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE IF NOT EXISTS user_roles_id_seq")
    op.alter_column(
        "user_roles", "id", server_default=sa.text("nextval('user_roles_id_seq')")
    )
    op.execute(
        """
        UPDATE user_roles
        SET id = nextval('user_roles_id_seq')
        WHERE id IS NULL
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_roles", "id", server_default=None)
    op.execute("DROP SEQUENCE IF EXISTS user_roles_id_seq")
    # ### end Alembic commands ###
