"""add ratings table

Revision ID: d2412df0d4a8
Revises: 8538b9e3664b
Create Date: 2026-04-06 20:45:41.898079

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2412df0d4a8"
down_revision: Union[str, Sequence[str], None] = "8538b9e3664b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ratings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column(
            "target_type", sa.Enum("TASK", "GROUP", name="ratingtarget"), nullable=False
        ),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "target_id", "target_type", name="uq_user_target_rating"
        ),
    )
    op.create_index(
        op.f("ix_ratings_target_id"), "ratings", ["target_id"], unique=False
    )
    op.create_index(op.f("ix_ratings_user_id"), "ratings", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ratings_user_id"), table_name="ratings")
    op.drop_index(op.f("ix_ratings_target_id"), table_name="ratings")
    op.drop_table("ratings")
    # ### end Alembic commands ###
