"""add contextual roles and constraints

Revision ID: eca64f6fa2dd
Revises: 0a000f0839e3
Create Date: 2026-03-27 04:10:35.303657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eca64f6fa2dd'
down_revision: Union[str, Sequence[str], None] = '0a000f0839e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_assignees', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('user_group_memberships', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('uq_user_group_membership', 'user_group_memberships', ['user_id', 'group_id'])
    op.create_index(op.f('ix_user_groups_admin_id'), 'user_groups', ['admin_id'], unique=False)
    op.add_column('user_roles', sa.Column('task_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_user_role_group'), 'user_roles', type_='unique')
    op.create_index(op.f('ix_user_roles_task_id'), 'user_roles', ['task_id'], unique=False)
    op.create_unique_constraint('uq_user_role_group_task', 'user_roles', ['user_id', 'role_id', 'group_id', 'task_id'])
    op.create_foreign_key(None, 'user_roles', 'tasks', ['task_id'], ['id'])
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint('uq_user_role_group_task', 'user_roles', type_='unique')
    op.drop_index(op.f('ix_user_roles_task_id'), table_name='user_roles')
    op.create_unique_constraint(op.f('uq_user_role_group'), 'user_roles', ['user_id', 'role_id', 'group_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_roles', 'task_id')
    op.drop_index(op.f('ix_user_groups_admin_id'), table_name='user_groups')
    op.drop_constraint('uq_user_group_membership', 'user_group_memberships', type_='unique')
    op.drop_column('user_group_memberships', 'created_at')
    op.alter_column('task_assignees', 'assigned_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
