"""add join_requests and group join_policy

Revision ID: ed1cc5c53f35
Revises: d2e3f4a5b6c7
Create Date: 2026-04-04 18:51:21.173470

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed1cc5c53f35"
down_revision: Union[str, Sequence[str], None] = "d2e3f4a5b6c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE joinpolicy AS ENUM ('OPEN', 'REQUEST')")

    op.create_table(
        "join_requests",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="joinrequeststatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["user_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "group_id", "task_id", name="uq_user_group_task_join_request"
        ),
    )
    op.create_index(
        op.f("ix_join_requests_group_id"), "join_requests", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_join_requests_status"), "join_requests", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_join_requests_task_id"), "join_requests", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_join_requests_user_id"), "join_requests", ["user_id"], unique=False
    )
    op.add_column(
        "user_groups",
        sa.Column(
            "join_policy", sa.Enum("OPEN", "REQUEST", name="joinpolicy"), nullable=False
        ),
    )
    op.create_index(
        op.f("ix_user_groups_join_policy"), "user_groups", ["join_policy"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_groups_join_policy"), table_name="user_groups")
    op.drop_column("user_groups", "join_policy")
    op.drop_index(op.f("ix_join_requests_user_id"), table_name="join_requests")
    op.drop_index(op.f("ix_join_requests_task_id"), table_name="join_requests")
    op.drop_index(op.f("ix_join_requests_status"), table_name="join_requests")
    op.drop_index(op.f("ix_join_requests_group_id"), table_name="join_requests")
    op.drop_table("join_requests")
    # ### end Alembic commands ###
