"""create task_assignees and enhance permissions and user_roles.group_id

Revision ID: ed2b72d685b4
Revises: ad892f317784
Create Date: 2026-03-22 22:20:02.197143

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed2b72d685b4"
down_revision: Union[str, Sequence[str], None] = "ad892f317784"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_assignees",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "permissions", sa.Column("context", sa.String(length=50), nullable=True)
    )
    op.alter_column(
        "permissions",
        "description",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_permissions_context"), "permissions", ["context"], unique=False
    )
    op.drop_index(op.f("ix_tasks_owner_id"), table_name="tasks")
    op.drop_constraint(op.f("tasks_owner_id_fkey"), "tasks", type_="foreignkey")
    op.drop_column("tasks", "owner_id")
    op.add_column("user_roles", sa.Column("group_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_user_roles_group_id"), "user_roles", ["group_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_user_role_group", "user_roles", ["user_id", "role_id", "group_id"]
    )
    op.create_foreign_key(None, "user_roles", "user_groups", ["group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_roles", type_="foreignkey")
    op.drop_constraint("uq_user_role_group", "user_roles", type_="unique")
    op.drop_index(op.f("ix_user_roles_group_id"), table_name="user_roles")
    op.drop_column("user_roles", "group_id")
    op.add_column(
        "tasks",
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("tasks_owner_id_fkey"), "tasks", "users", ["owner_id"], ["id"]
    )
    op.create_index(op.f("ix_tasks_owner_id"), "tasks", ["owner_id"], unique=False)
    op.drop_index(op.f("ix_permissions_context"), table_name="permissions")
    op.alter_column(
        "permissions",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_column("permissions", "context")
    op.drop_table("task_assignees")
    # ### end Alembic commands ###
