"""add subgroups visibility and difficulty

Revision ID: f1ed549f1e64
Revises: 71a7c62aea57
Create Date: 2026-03-31 11:58:56.802064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ed549f1e64'
down_revision: Union[str, Sequence[str], None] = '71a7c62aea57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types if they don't exist
    op.execute("CREATE TYPE taskdifficulty AS ENUM ('EASY', 'MEDIUM', 'HARD')")
    op.execute("CREATE TYPE taskvisibility AS ENUM ('PUBLIC', 'PRIVATE', 'GROUP')")
    op.execute("CREATE TYPE groupvisibility AS ENUM ('PUBLIC', 'PRIVATE')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='taskdifficulty'), nullable=True))
    op.add_column('tasks', sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', 'GROUP', name='taskvisibility'), nullable=False))
    op.create_index(op.f('ix_tasks_visibility'), 'tasks', ['visibility'], unique=False)
    op.add_column('user_groups', sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='groupvisibility'), nullable=False))
    op.add_column('user_groups', sa.Column('parent_group_id', sa.Integer(), nullable=True))
    op.add_column('user_groups', sa.Column('level', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_user_groups_parent_group_id'), 'user_groups', ['parent_group_id'], unique=False)
    op.create_index(op.f('ix_user_groups_visibility'), 'user_groups', ['visibility'], unique=False)
    op.create_foreign_key(None, 'user_groups', 'user_groups', ['parent_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.drop_index(op.f('ix_user_groups_visibility'), table_name='user_groups')
    op.drop_index(op.f('ix_user_groups_parent_group_id'), table_name='user_groups')
    op.drop_column('user_groups', 'level')
    op.drop_column('user_groups', 'parent_group_id')
    op.drop_column('user_groups', 'visibility')
    op.drop_index(op.f('ix_tasks_visibility'), table_name='tasks')
    op.drop_column('tasks', 'visibility')
    op.drop_column('tasks', 'difficulty')
    # ### end Alembic commands ###
