"""add xp today and task indexes

Revision ID: fe26ffbcdc08
Revises: d2412df0d4a8
Create Date: 2026-04-11 10:19:11.383649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe26ffbcdc08'
down_revision: Union[str, Sequence[str], None] = 'd2412df0d4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_taskassignee_task', 'task_assignees', ['task_id'], unique=False)
    op.create_index('idx_taskassignee_user', 'task_assignees', ['user_id'], unique=False)
    op.create_index('idx_task_active_group', 'tasks', ['is_active', 'group_id'], unique=False)
    op.create_index('idx_task_created_updated', 'tasks', ['created_at', 'updated_at'], unique=False)
    op.create_index('idx_task_group_status_priority', 'tasks', ['group_id', 'status', 'priority'], unique=False)
    op.add_column('user_skills', sa.Column('xp_today', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_skills', 'xp_today')
    op.drop_index('idx_task_group_status_priority', table_name='tasks')
    op.drop_index('idx_task_created_updated', table_name='tasks')
    op.drop_index('idx_task_active_group', table_name='tasks')
    op.drop_index('idx_taskassignee_user', table_name='task_assignees')
    op.drop_index('idx_taskassignee_task', table_name='task_assignees')
    # ### end Alembic commands ###
